-- RetainIQ Pipeline — Postgres Schema
-- Generated by src/storage/postgres_setup.py
-- Run: venv/Scripts/python -c "from src.storage.postgres_setup import create_all; create_all()"

CREATE TABLE IF NOT EXISTS fact_mobile_money_tx (
    transaction_id                VARCHAR(60)   PRIMARY KEY,
    wallet_id                     VARCHAR(20)   NOT NULL,
    timestamp                     TIMESTAMPTZ,
    transaction_type              VARCHAR(20),
    amount_ngn                    NUMERIC(15,2),
    fee_ngn                       NUMERIC(10,2),
    balance_after_ngn             NUMERIC(18,2),
    agent_id                      VARCHAR(60),
    channel                       VARCHAR(20),
    device_os                     VARCHAR(20),
    kyc_tier                      VARCHAR(10),
    fraud_flag                    BOOLEAN,
    churn_30d                     BOOLEAN,
    is_amount_ngn_outlier         BOOLEAN DEFAULT FALSE,
    is_fee_ngn_outlier            BOOLEAN DEFAULT FALSE,
    is_balance_after_ngn_outlier  BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS fact_xml_transactions (
    transaction_id               BIGINT        PRIMARY KEY,
    status                       VARCHAR(5),
    reference_number             VARCHAR(60),
    partner_reference_number     VARCHAR(60),
    capture_number               VARCHAR(60),
    receipt_number               VARCHAR(60)   UNIQUE,
    customer_id                  VARCHAR(20),
    wallet_id                    VARCHAR(20)   NOT NULL,
    phone_number                 VARCHAR(64),
    created_by                   VARCHAR(20),
    transaction_type             VARCHAR(20),
    journal_type                 VARCHAR(10),
    category                     VARCHAR(50),
    currency                     VARCHAR(5)    DEFAULT 'IDR',
    net_amount                   BIGINT,
    fee_internal_amount          BIGINT,
    fee_external_amount          BIGINT,
    total_fee                    BIGINT,
    channel                      VARCHAR(20),
    channel_reference_number     VARCHAR(60),
    is_verified                  BOOLEAN,
    note                         TEXT,
    detail                       TEXT,
    paying_at                    TIMESTAMPTZ,
    created_at                   TIMESTAMPTZ,
    updated_at                   TIMESTAMPTZ,
    is_ref_dup                   BOOLEAN       DEFAULT FALSE,
    date_order_anomaly           BOOLEAN       DEFAULT FALSE,
    is_net_amount_outlier        BOOLEAN       DEFAULT FALSE,
    is_total_fee_outlier         BOOLEAN       DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS dim_wallet_agg_mm (
    wallet_id          VARCHAR(20)   PRIMARY KEY,
    total_tx_count     INTEGER,
    total_volume_ngn   NUMERIC(20,2),
    total_fees_ngn     NUMERIC(15,2),
    avg_tx_amount      NUMERIC(15,2),
    first_tx_date      DATE,
    last_tx_date       DATE,
    dominant_channel   VARCHAR(20),
    dominant_tx_type   VARCHAR(20),
    fraud_flag         BOOLEAN,
    churn_30d          BOOLEAN
);

CREATE TABLE IF NOT EXISTS dim_wallet_agg_xml (
    wallet_id           VARCHAR(20)   PRIMARY KEY,
    xml_tx_count        INTEGER,
    xml_total_volume    BIGINT,
    xml_total_fees      BIGINT,
    xml_first_tx_date   DATE,
    xml_last_tx_date    DATE
);

CREATE TABLE IF NOT EXISTS dim_unified_wallet (
    wallet_id            VARCHAR(20)   PRIMARY KEY,
    full_name            VARCHAR(120),
    age                  SMALLINT,
    gender               VARCHAR(10),
    state                VARCHAR(60),
    city                 VARCHAR(80),
    registration_date    DATE,
    account_status       VARCHAR(20),
    preferred_language   VARCHAR(30),
    linked_bank          VARCHAR(60),
    support_tier         VARCHAR(20),
    kyc_tier             VARCHAR(10),
    acquisition_channel  VARCHAR(40),
    has_xml_activity     BOOLEAN       DEFAULT FALSE,
    total_tx_count       INTEGER,
    total_volume_ngn     NUMERIC(20,2),
    total_fees_ngn       NUMERIC(15,2),
    avg_tx_amount        NUMERIC(15,2),
    first_tx_date        DATE,
    last_tx_date         DATE,
    dominant_channel     VARCHAR(20),
    dominant_tx_type     VARCHAR(20),
    fraud_flag           BOOLEAN,
    churn_30d            BOOLEAN
);
